# Generated by Django 5.2.1 on 2025-07-04 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
