# Generated by Django 5.2.1 on 2025-07-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_useraddress_delete_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='is_default',
            field=models.BooleanField(default=True),
        ),
    ]
